# Generated by Django 4.1.3 on 2022-11-22 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ThoughtsApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thoughts',
            old_name='user_id',
            new_name='user',
        ),
    ]
